# Generated by Django 4.0.2 on 2022-02-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=267)),
                ('price', models.IntegerField()),
                ('src', models.URLField(max_length=267)),
            ],
        ),
    ]
