# Generated by Django 4.0.2 on 2022-02-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_price_orderitem_subtotal_remove_orderitem_src_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
